### ISSUE TITLE
想请问多集群初始化的问题

### ISSUE THREAD

**Issue by googs1025** [20gu00/aBais#1]
目前也想做关于多集群的管理系统，想问一下这个项目的多集群是如何管理呢？
是用一个类似map[string]*clientSet 的方式保存并操作多个集群嘛？

另外，如果有机会想加一个微信，可以交流交流～

**Comment by googs1025** [comment]
看了一下代码，确实也是这个想法～

**Comment by 20gu00** [comment]
对的，多集群那里直接直接将各个配置写进map来使用。微信aBai13018597889
